apiVersion: v2
name: fitsync-chart
description: A Helm chart for the FitSync Microservices Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 17.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled