{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fitsync-routes
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  - {{ .Values.gateway.domain | quote }}
  rules:
  # Route for API Gateway
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: api-gateway
      port: 4000
  
  # Route for Frontend (Catch-all)
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 3000
{{- end }}